// Generated by train_iso_forest.py from data/normal_log.csv. Do not edit.
#ifndef ISOLATION_FOREST_H
#define ISOLATION_FOREST_H

#include <math.h>

// Input vector layout (must match toFeatureVector() in isolation_forest_data.h):
//   [ 0] displacementX_mm / 1000
//   [ 1] displacementY_mm / 1000
//   [ 2] displacementZ_mm / 1000
//   [ 3] accX_mmss2 / 1000
//   [ 4] accY_mmss2 / 1000
//   [ 5] accZ_mmss2 / 1000
//   [ 6] resultantAccel / 1000
//   [ 7] rateRollDegS / 10
//   [ 8] ratePitchDegS / 10
//   [ 9] rateYawDegS / 10
//   [10] angleRoll / 10
//   [11] anglePitch / 10
//   [12] angleYaw / 10
//   [13] vibrationDetected / 1
//   [14] isHighPrecision / 1
#define ISOLATION_FOREST_N_FEATURES 15

static inline float isolation_forest_average_path_length(int n_samples) {
    if (n_samples <= 1) return 0.0f;
    if (n_samples == 2) return 1.0f;
    return 2.0f * (logf((float)(n_samples - 1)) + 0.5772156649f) -
           2.0f * (float)(n_samples - 1) / (float)n_samples;
}

static const int iso_tree_0_left[] = {1, 2, 3, -1, 5, -1, -1, 8, -1, -1, 11, 12, -1, -1, 15, 16, -1, -1, 19, -1, -1};
static const int iso_tree_0_right[] = {10, 7, 4, -1, 6, -1, -1, 9, -1, -1, 14, 13, -1, -1, 18, 17, -1, -1, 20, -1, -1};
static const int iso_tree_0_feature[] = {5, 9, 1, -2, 3, -2, -2, 1, -2, -2, 4, 8, -2, -2, 12, 3, -2, -2, 9, -2, -2};
static const int iso_tree_0_samples[] = {15, 7, 5, 1, 4, 1, 3, 2, 1, 1, 8, 2, 1, 1, 6, 3, 2, 1, 3, 2, 1};
static const float iso_tree_0_threshold[] = {9.80681992f, 0.299475402f, 0.0109861912f, -2.0f, 0.0950054079f, -2.0f, -2.0f, 0.0121819805f, -2.0f, -2.0f, 0.0338000394f, -0.90183562f, -2.0f, -2.0f, 17.9752541f, 0.106938981f, -2.0f, -2.0f, 0.124460511f, -2.0f, -2.0f};
static const int iso_tree_0_nodes = 21;

static const int iso_tree_1_left[] = {1, 2, 3, -1, 5, -1, -1, 8, -1, 10, -1, -1, 13, 14, -1, -1, 17, -1, 19, -1, -1};
static const int iso_tree_1_right[] = {12, 7, 4, -1, 6, -1, -1, 9, -1, 11, -1, -1, 16, 15, -1, -1, 18, -1, 20, -1, -1};
static const int iso_tree_1_feature[] = {0, 5, 5, -2, 3, -2, -2, 11, -2, 1, -2, -2, 5, 11, -2, -2, 7, -2, 10, -2, -2};
static const int iso_tree_1_samples[] = {15, 8, 4, 1, 3, 2, 1, 4, 1, 3, 1, 2, 7, 2, 1, 1, 5, 1, 4, 2, 2};
static const float iso_tree_1_threshold[] = {0.0123462761f, 9.80315876f, 9.79535389f, -2.0f, 0.097621657f, -2.0f, -2.0f, 2.01129627f, -2.0f, 0.0146466307f, -2.0f, -2.0f, 9.80064678f, 2.23059154f, -2.0f, -2.0f, 0.594533086f, -2.0f, 1.40002549f, -2.0f, -2.0f};
static const int iso_tree_1_nodes = 21;

static const int iso_tree_2_left[] = {1, 2, -1, 4, 5, -1, -1, 8, -1, -1, 11, 12, 13, -1, -1, 16, -1, -1, 19, -1, -1};
static const int iso_tree_2_right[] = {10, 3, -1, 7, 6, -1, -1, 9, -1, -1, 18, 15, 14, -1, -1, 17, -1, -1, 20, -1, -1};
static const int iso_tree_2_feature[] = {10, 9, -2, 12, 11, -2, -2, 10, -2, -2, 2, 9, 2, -2, -2, 11, -2, -2, 3, -2, -2};
static const int iso_tree_2_samples[] = {15, 6, 1, 5, 2, 1, 1, 3, 1, 2, 9, 7, 4, 2, 2, 3, 1, 2, 2, 1, 1};
static const float iso_tree_2_threshold[] = {1.46901035f, -0.343776584f, -2.0f, 17.933239f, 2.1584909f, -2.0f, -2.0f, 1.30965078f, -2.0f, -2.0f, 0.983489275f, 0.225815624f, 0.978582501f, -2.0f, -2.0f, 2.002599f, -2.0f, -2.0f, 0.0947660357f, -2.0f, -2.0f};
static const int iso_tree_2_nodes = 21;

static const int iso_tree_3_left[] = {1, 2, 3, -1, 5, -1, -1, 8, -1, -1, 11, -1, 13, 14, -1, -1, 17, -1, -1};
static const int iso_tree_3_right[] = {10, 7, 4, -1, 6, -1, -1, 9, -1, -1, 12, -1, 16, 15, -1, -1, 18, -1, -1};
static const int iso_tree_3_feature[] = {8, 1, 8, -2, 9, -2, -2, 8, -2, -2, 6, -2, 1, 7, -2, -2, 11, -2, -2};
static const int iso_tree_3_samples[] = {15, 5, 3, 1, 2, 1, 1, 2, 1, 1, 10, 1, 9, 5, 3, 2, 4, 1, 3};
static const float iso_tree_3_threshold[] = {-0.168009639f, 0.0121378331f, -0.816924095f, -2.0f, 0.210332885f, -2.0f, -2.0f, -0.800563812f, -2.0f, -2.0f, 9.7964201f, -2.0f, 0.0145392343f, 0.568736374f, -2.0f, -2.0f, 2.09221959f, -2.0f, -2.0f};
static const int iso_tree_3_nodes = 19;

static const int iso_tree_4_left[] = {1, 2, 3, -1, 5, -1, -1, 8, -1, 10, -1, -1, 13, 14, -1, 16, -1, -1, 19, 20, -1, -1, 23, -1, -1};
static const int iso_tree_4_right[] = {12, 7, 4, -1, 6, -1, -1, 9, -1, 11, -1, -1, 18, 15, -1, 17, -1, -1, 22, 21, -1, -1, 24, -1, -1};
static const int iso_tree_4_feature[] = {4, 8, 10, -2, 9, -2, -2, 9, -2, 5, -2, -2, 5, 6, -2, 4, -2, -2, 3, 6, -2, -2, 2, -2, -2};
static const int iso_tree_4_samples[] = {15, 7, 4, 1, 3, 1, 2, 3, 1, 2, 1, 1, 8, 4, 1, 3, 1, 2, 4, 2, 1, 1, 2, 1, 1};
static const float iso_tree_4_threshold[] = {-0.0130599029f, 0.59273833f, 1.34383583f, -2.0f, -0.313281119f, -2.0f, -2.0f, -0.530131936f, -2.0f, 9.7946806f, -2.0f, -2.0f, 9.81110382f, 9.80421352f, -2.0f, 0.046699997f, -2.0f, -2.0f, 0.106620759f, 9.81952572f, -2.0f, -2.0f, 0.982035995f, -2.0f, -2.0f};
static const int iso_tree_4_nodes = 25;

static const int iso_tree_5_left[] = {1, 2, -1, 4, 5, -1, -1, -1, 9, -1, 11, 12, -1, -1, 15, -1, -1};
static const int iso_tree_5_right[] = {8, 3, -1, 7, 6, -1, -1, -1, 10, -1, 14, 13, -1, -1, 16, -1, -1};
static const int iso_tree_5_feature[] = {5, 10, -2, 0, 12, -2, -2, -2, 2, -2, 2, 4, -2, -2, 10, -2, -2};
static const int iso_tree_5_samples[] = {15, 10, 1, 9, 8, 6, 2, 1, 5, 1, 4, 2, 1, 1, 2, 1, 1};
static const float iso_tree_5_threshold[] = {9.81398106f, 1.32326722f, -2.0f, 0.0154581899f, 18.0983295f, -2.0f, -2.0f, -2.0f, 0.977481842f, -2.0f, 0.978754103f, 0.0503191464f, -2.0f, -2.0f, 1.49003065f, -2.0f, -2.0f};
static const int iso_tree_5_nodes = 17;

static const int iso_tree_6_left[] = {1, -1, 3, 4, -1, 6, -1, -1, 9, 10, -1, -1, 13, -1, -1};
static const int iso_tree_6_right[] = {2, -1, 8, 5, -1, 7, -1, -1, 12, 11, -1, -1, 14, -1, -1};
static const int iso_tree_6_feature[] = {5, -2, 0, 10, -2, 6, -2, -2, 0, 8, -2, -2, 6, -2, -2};
static const int iso_tree_6_samples[] = {15, 1, 14, 5, 1, 4, 2, 2, 9, 2, 1, 1, 7, 1, 6};
static const float iso_tree_6_threshold[] = {9.79290295f, -2.0f, 0.0119287837f, 1.4108808f, -2.0f, 9.81044674f, -2.0f, -2.0f, 0.0123057403f, 0.622169435f, -2.0f, -2.0f, 9.79653454f, -2.0f, -2.0f};
static const int iso_tree_6_nodes = 15;

static const int iso_tree_7_left[] = {1, 2, 3, -1, -1, 6, -1, -1, 9, 10, 11, -1, -1, 14, -1, -1, 17, 18, -1, -1, 21, -1, -1};
static const int iso_tree_7_right[] = {8, 5, 4, -1, -1, 7, -1, -1, 16, 13, 12, -1, -1, 15, -1, -1, 20, 19, -1, -1, 22, -1, -1};
static const int iso_tree_7_feature[] = {0, 6, 0, -2, -2, 12, -2, -2, 2, 11, 1, -2, -2, 8, -2, -2, 7, 4, -2, -2, 4, -2, -2};
static const int iso_tree_7_samples[] = {15, 4, 2, 1, 1, 2, 1, 1, 11, 5, 3, 2, 1, 2, 1, 1, 6, 2, 1, 1, 4, 1, 3};
static const float iso_tree_7_threshold[] = {0.0109986477f, 9.81109142f, 0.00823880546f, -2.0f, -2.0f, 17.9829731f, -2.0f, -2.0f, 0.980326891f, 2.04053569f, 0.0107814576f, -2.0f, -2.0f, 0.641281426f, -2.0f, -2.0f, 0.460219055f, -0.045899678f, -2.0f, -2.0f, 0.043697428f, -2.0f, -2.0f};
static const int iso_tree_7_nodes = 23;

static const int iso_tree_8_left[] = {1, -1, 3, 4, 5, -1, -1, 8, -1, -1, 11, 12, -1, -1, 15, -1, -1};
static const int iso_tree_8_right[] = {2, -1, 10, 7, 6, -1, -1, 9, -1, -1, 14, 13, -1, -1, 16, -1, -1};
static const int iso_tree_8_feature[] = {6, -2, 9, 2, 6, -2, -2, 5, -2, -2, 8, 5, -2, -2, 2, -2, -2};
static const int iso_tree_8_samples[] = {15, 1, 14, 7, 2, 1, 1, 5, 2, 3, 7, 3, 2, 1, 4, 3, 1};
static const float iso_tree_8_threshold[] = {9.79530621f, -2.0f, 0.0865174755f, 0.978420615f, 9.82728577f, -2.0f, -2.0f, 9.79855633f, -2.0f, -2.0f, 0.808710396f, 9.82023621f, -2.0f, -2.0f, 0.982300758f, -2.0f, -2.0f};
static const int iso_tree_8_nodes = 17;

static const int iso_tree_9_left[] = {1, 2, 3, 4, -1, -1, 7, -1, -1, 10, 11, -1, -1, 14, -1, -1, 17, -1, -1};
static const int iso_tree_9_right[] = {16, 9, 6, 5, -1, -1, 8, -1, -1, 13, 12, -1, -1, 15, -1, -1, 18, -1, -1};
static const int iso_tree_9_feature[] = {11, 4, 12, 1, -2, -2, 10, -2, -2, 8, 1, -2, -2, 2, -2, -2, 10, -2, -2};
static const int iso_tree_9_samples[] = {15, 13, 4, 2, 1, 1, 2, 1, 1, 9, 6, 3, 3, 3, 2, 1, 2, 1, 1};
static const float iso_tree_9_threshold[] = {2.25556111f, -0.0387910791f, 18.0250778f, 0.0101521257f, -2.0f, -2.0f, 1.49073613f, -2.0f, -2.0f, 0.84683609f, 0.0135511979f, -2.0f, -2.0f, 0.983578146f, -2.0f, -2.0f, 1.36402607f, -2.0f, -2.0f};
static const int iso_tree_9_nodes = 19;

static const int iso_tree_10_left[] = {1, 2, 3, -1, -1, 6, 7, -1, -1, -1, 11, 12, -1, 14, -1, -1, -1};
static const int iso_tree_10_right[] = {10, 5, 4, -1, -1, 9, 8, -1, -1, -1, 16, 13, -1, 15, -1, -1, -1};
static const int iso_tree_10_feature[] = {11, 0, 12, -2, -2, 8, 1, -2, -2, -2, 5, 0, -2, 0, -2, -2, -2};
static const int iso_tree_10_samples[] = {15, 5, 2, 1, 1, 3, 2, 1, 1, 1, 10, 9, 1, 8, 2, 6, 1};
static const float iso_tree_10_threshold[] = {2.00009394f, 0.0123718521f, 17.9326153f, -2.0f, -2.0f, 0.604397655f, 0.011137858f, -2.0f, -2.0f, -2.0f, 9.81513977f, 0.00951624848f, -2.0f, 0.0114650019f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_10_nodes = 17;

static const int iso_tree_11_left[] = {1, 2, 3, 4, -1, -1, 7, -1, -1, 10, 11, -1, -1, -1, 15, 16, -1, 18, -1, -1, 21, -1, -1};
static const int iso_tree_11_right[] = {14, 9, 6, 5, -1, -1, 8, -1, -1, 13, 12, -1, -1, -1, 20, 17, -1, 19, -1, -1, 22, -1, -1};
static const int iso_tree_11_feature[] = {12, 4, 12, 4, -2, -2, 7, -2, -2, 1, 2, -2, -2, -2, 1, 11, -2, 9, -2, -2, 7, -2, -2};
static const int iso_tree_11_samples[] = {15, 10, 5, 2, 1, 1, 3, 2, 1, 5, 4, 1, 3, 1, 5, 3, 1, 2, 1, 1, 2, 1, 1};
static const float iso_tree_11_threshold[] = {18.0289021f, 0.0473101139f, 17.9362354f, 0.045385588f, -2.0f, -2.0f, -0.546232879f, -2.0f, -2.0f, 0.0177675597f, 0.980511546f, -2.0f, -2.0f, -2.0f, 0.0132427644f, 2.14980984f, -2.0f, 0.5340994f, -2.0f, -2.0f, 0.36201492f, -2.0f, -2.0f};
static const int iso_tree_11_nodes = 23;

static const int iso_tree_12_left[] = {1, 2, 3, -1, 5, -1, -1, 8, -1, 10, -1, -1, 13, 14, -1, -1, 17, 18, -1, -1, -1};
static const int iso_tree_12_right[] = {12, 7, 4, -1, 6, -1, -1, 9, -1, 11, -1, -1, 16, 15, -1, -1, 20, 19, -1, -1, -1};
static const int iso_tree_12_feature[] = {12, 0, 0, -2, 8, -2, -2, 10, -2, 7, -2, -2, 2, 9, -2, -2, 3, 11, -2, -2, -2};
static const int iso_tree_12_samples[] = {15, 10, 7, 1, 6, 2, 4, 3, 1, 2, 1, 1, 5, 2, 1, 1, 3, 2, 1, 1, 1};
static const float iso_tree_12_threshold[] = {18.0216522f, 0.0125865722f, 0.00972678419f, -2.0f, -0.302069634f, -2.0f, -2.0f, 1.41623223f, -2.0f, 1.19186306f, -2.0f, -2.0f, 0.978903353f, 0.464972168f, -2.0f, -2.0f, 0.0981369019f, 2.25528669f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_12_nodes = 21;

static const int iso_tree_13_left[] = {1, 2, 3, -1, 5, -1, -1, -1, 9, 10, -1, 12, -1, -1, -1};
static const int iso_tree_13_right[] = {8, 7, 4, -1, 6, -1, -1, -1, 14, 11, -1, 13, -1, -1, -1};
static const int iso_tree_13_feature[] = {4, 3, 2, -2, 1, -2, -2, -2, 3, 2, -2, 9, -2, -2, -2};
static const int iso_tree_13_samples[] = {15, 7, 6, 1, 5, 4, 1, 1, 8, 7, 1, 6, 4, 2, 1};
static const float iso_tree_13_threshold[] = {-0.0300281551f, 0.0971628651f, 0.977907896f, -2.0f, 0.0133425668f, -2.0f, -2.0f, -2.0f, 0.108838521f, 0.979947031f, -2.0f, 0.201847479f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_13_nodes = 15;

static const int iso_tree_14_left[] = {1, -1, 3, 4, 5, -1, -1, -1, 9, 10, -1, -1, -1};
static const int iso_tree_14_right[] = {2, -1, 8, 7, 6, -1, -1, -1, 12, 11, -1, -1, -1};
static const int iso_tree_14_feature[] = {5, -2, 8, 2, 0, -2, -2, -2, 8, 4, -2, -2, -2};
static const int iso_tree_14_samples[] = {15, 1, 14, 4, 3, 2, 1, 1, 10, 9, 4, 5, 1};
static const float iso_tree_14_threshold[] = {9.79362392f, -2.0f, 0.143082738f, 0.978300214f, 0.0123256352f, -2.0f, -2.0f, -2.0f, 1.38000643f, 0.0253414046f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_14_nodes = 13;

static const int iso_tree_15_left[] = {1, 2, 3, -1, 5, -1, -1, 8, -1, 10, -1, -1, 13, -1, 15, 16, -1, -1, -1};
static const int iso_tree_15_right[] = {12, 7, 4, -1, 6, -1, -1, 9, -1, 11, -1, -1, 14, -1, 18, 17, -1, -1, -1};
static const int iso_tree_15_feature[] = {2, 6, 7, -2, 4, -2, -2, 1, -2, 5, -2, -2, 1, -2, 1, 4, -2, -2, -2};
static const int iso_tree_15_samples[] = {15, 11, 7, 1, 6, 2, 4, 4, 1, 3, 1, 2, 4, 1, 3, 2, 1, 1, 1};
static const float iso_tree_15_threshold[] = {0.982289314f, 9.81809711f, -0.98159337f, -2.0f, -0.013532754f, -2.0f, -2.0f, 0.0114718238f, -2.0f, 9.81997204f, -2.0f, -2.0f, 0.0130421137f, -2.0f, 0.0161014181f, -0.0232262537f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_15_nodes = 19;

static const int iso_tree_16_left[] = {1, 2, 3, -1, 5, -1, -1, 8, 9, -1, -1, -1, 13, -1, -1};
static const int iso_tree_16_right[] = {12, 7, 4, -1, 6, -1, -1, 11, 10, -1, -1, -1, 14, -1, -1};
static const int iso_tree_16_feature[] = {4, 2, 2, -2, 4, -2, -2, 8, 11, -2, -2, -2, 9, -2, -2};
static const int iso_tree_16_samples[] = {15, 13, 8, 1, 7, 4, 3, 5, 4, 2, 2, 1, 2, 1, 1};
static const float iso_tree_16_threshold[] = {0.054795254f, 0.98124063f, 0.977576435f, -2.0f, 0.0463155136f, -2.0f, -2.0f, 1.10774827f, 2.16237092f, -2.0f, -2.0f, -2.0f, 0.0667501464f, -2.0f, -2.0f};
static const int iso_tree_16_nodes = 15;

static const int iso_tree_17_left[] = {1, 2, 3, -1, 5, -1, -1, 8, 9, -1, -1, 12, -1, -1, 15, 16, 17, -1, -1, -1, 21, 22, -1, -1, -1};
static const int iso_tree_17_right[] = {14, 7, 4, -1, 6, -1, -1, 11, 10, -1, -1, 13, -1, -1, 20, 19, 18, -1, -1, -1, 24, 23, -1, -1, -1};
static const int iso_tree_17_feature[] = {4, 10, 10, -2, 7, -2, -2, 11, 0, -2, -2, 5, -2, -2, 6, 12, 8, -2, -2, -2, 4, 3, -2, -2, -2};
static const int iso_tree_17_samples[] = {15, 7, 3, 1, 2, 1, 1, 4, 2, 1, 1, 2, 1, 1, 8, 3, 2, 1, 1, 1, 5, 4, 3, 1, 1};
static const float iso_tree_17_threshold[] = {-0.0262720156f, 1.46026194f, 1.38504601f, -2.0f, -0.809026957f, -2.0f, -2.0f, 2.09127808f, 0.0114911143f, -2.0f, -2.0f, 9.81657791f, -2.0f, -2.0f, 9.81138992f, 17.9750957f, 0.991352439f, -2.0f, -2.0f, -2.0f, 0.0601466f, 0.10725753f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_17_nodes = 25;

static const int iso_tree_18_left[] = {1, 2, -1, -1, 5, 6, 7, -1, -1, 10, -1, -1, 13, 14, -1, -1, -1};
static const int iso_tree_18_right[] = {4, 3, -1, -1, 12, 9, 8, -1, -1, 11, -1, -1, 16, 15, -1, -1, -1};
static const int iso_tree_18_feature[] = {1, 5, -2, -2, 3, 4, 11, -2, -2, 4, -2, -2, 6, 2, -2, -2, -2};
static const int iso_tree_18_samples[] = {15, 2, 1, 1, 13, 9, 6, 5, 1, 3, 1, 2, 4, 3, 2, 1, 1};
static const float iso_tree_18_threshold[] = {0.0103658559f, 9.81315613f, -2.0f, -2.0f, 0.103689916f, -0.0171171315f, 2.20940781f, -2.0f, -2.0f, 0.04105106f, -2.0f, -2.0f, 9.82132053f, 0.982059479f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_18_nodes = 17;

static const int iso_tree_19_left[] = {1, 2, 3, 4, -1, -1, 7, -1, -1, 10, 11, -1, -1, 14, -1, -1, 17, -1, -1};
static const int iso_tree_19_right[] = {16, 9, 6, 5, -1, -1, 8, -1, -1, 13, 12, -1, -1, 15, -1, -1, 18, -1, -1};
static const int iso_tree_19_feature[] = {8, 9, 7, 6, -2, -2, 9, -2, -2, 0, 11, -2, -2, 12, -2, -2, 2, -2, -2};
static const int iso_tree_19_samples[] = {15, 13, 5, 3, 2, 1, 2, 1, 1, 8, 3, 1, 2, 5, 4, 1, 2, 1, 1};
static const float iso_tree_19_threshold[] = {1.25802934f, -0.0809003562f, -0.190606952f, 9.81931973f, -2.0f, -2.0f, -0.498888493f, -2.0f, -2.0f, 0.0109079899f, 2.05552053f, -2.0f, -2.0f, 18.077919f, -2.0f, -2.0f, 0.981567025f, -2.0f, -2.0f};
static const int iso_tree_19_nodes = 19;

static const int iso_tree_20_left[] = {1, 2, 3, -1, 5, -1, -1, 8, -1, 10, -1, -1, 13, 14, 15, -1, -1, 18, -1, -1, -1};
static const int iso_tree_20_right[] = {12, 7, 4, -1, 6, -1, -1, 9, -1, 11, -1, -1, 20, 17, 16, -1, -1, 19, -1, -1, -1};
static const int iso_tree_20_feature[] = {5, 2, 10, -2, 3, -2, -2, 6, -2, 2, -2, -2, 8, 4, 7, -2, -2, 9, -2, -2, -2};
static const int iso_tree_20_samples[] = {15, 10, 3, 1, 2, 1, 1, 7, 1, 6, 5, 1, 5, 4, 2, 1, 1, 2, 1, 1, 1};
static const float iso_tree_20_threshold[] = {9.81259632f, 0.980481744f, 1.42231238f, -2.0f, 0.0990196541f, -2.0f, -2.0f, 9.79625893f, -2.0f, 0.984029114f, -2.0f, -2.0f, 0.834384978f, 0.0127268173f, -0.368676066f, -2.0f, -2.0f, 0.259815842f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_20_nodes = 21;

static const int iso_tree_21_left[] = {1, 2, 3, 4, -1, -1, 7, -1, -1, -1, 11, 12, 13, -1, -1, 16, -1, -1, 19, 20, -1, -1, -1};
static const int iso_tree_21_right[] = {10, 9, 6, 5, -1, -1, 8, -1, -1, -1, 18, 15, 14, -1, -1, 17, -1, -1, 22, 21, -1, -1, -1};
static const int iso_tree_21_feature[] = {4, 4, 6, 6, -2, -2, 3, -2, -2, -2, 3, 0, 3, -2, -2, 11, -2, -2, 1, 2, -2, -2, -2};
static const int iso_tree_21_samples[] = {15, 7, 6, 4, 1, 3, 2, 1, 1, 1, 8, 5, 3, 2, 1, 2, 1, 1, 3, 2, 1, 1, 1};
static const float iso_tree_21_threshold[] = {0.000630633032f, -0.0376289673f, 9.80901527f, 9.79413033f, -2.0f, -2.0f, 0.0904284492f, -2.0f, -2.0f, -2.0f, 0.105619758f, 0.0126012592f, 0.10381043f, -2.0f, -2.0f, 2.29290867f, -2.0f, -2.0f, 0.0171809308f, 0.982440054f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_21_nodes = 23;

static const int iso_tree_22_left[] = {1, 2, 3, -1, -1, -1, 7, 8, -1, -1, 11, 12, -1, -1, 15, -1, -1};
static const int iso_tree_22_right[] = {6, 5, 4, -1, -1, -1, 10, 9, -1, -1, 14, 13, -1, -1, 16, -1, -1};
static const int iso_tree_22_feature[] = {2, 6, 0, -2, -2, -2, 8, 3, -2, -2, 2, 10, -2, -2, 0, -2, -2};
static const int iso_tree_22_samples[] = {15, 3, 2, 1, 1, 1, 12, 2, 1, 1, 10, 4, 2, 2, 6, 4, 2};
static const float iso_tree_22_threshold[] = {0.97824347f, 9.82794571f, 0.00931825582f, -2.0f, -2.0f, -2.0f, 0.453252345f, 0.102839902f, -2.0f, -2.0f, 0.981942236f, 1.41853774f, -2.0f, -2.0f, 0.0144795347f, -2.0f, -2.0f};
static const int iso_tree_22_nodes = 17;

static const int iso_tree_23_left[] = {1, 2, 3, 4, -1, -1, 7, -1, -1, -1, 11, 12, -1, 14, -1, -1, 17, -1, 19, -1, -1};
static const int iso_tree_23_right[] = {10, 9, 6, 5, -1, -1, 8, -1, -1, -1, 16, 13, -1, 15, -1, -1, 18, -1, 20, -1, -1};
static const int iso_tree_23_feature[] = {4, 1, 7, 8, -2, -2, 8, -2, -2, -2, 9, 4, -2, 12, -2, -2, 12, -2, 8, -2, -2};
static const int iso_tree_23_samples[] = {15, 7, 6, 4, 1, 3, 2, 1, 1, 1, 8, 5, 1, 4, 2, 2, 3, 1, 2, 1, 1};
static const float iso_tree_23_threshold[] = {-0.0173119493f, 0.0134042846f, -0.427528203f, -0.0773238689f, -2.0f, -2.0f, -0.878967404f, -2.0f, -2.0f, -2.0f, 0.217365146f, 0.042939879f, -2.0f, 17.9452934f, -2.0f, -2.0f, 17.9842033f, -2.0f, 1.29213285f, -2.0f, -2.0f};
static const int iso_tree_23_nodes = 21;

static const int iso_tree_24_left[] = {1, 2, -1, -1, 5, 6, 7, -1, -1, 10, -1, -1, 13, 14, -1, -1, 17, -1, -1};
static const int iso_tree_24_right[] = {4, 3, -1, -1, 12, 9, 8, -1, -1, 11, -1, -1, 16, 15, -1, -1, 18, -1, -1};
static const int iso_tree_24_feature[] = {3, 2, -2, -2, 4, 4, 9, -2, -2, 10, -2, -2, 11, 3, -2, -2, 0, -2, -2};
static const int iso_tree_24_samples[] = {15, 2, 1, 1, 13, 5, 2, 1, 1, 3, 1, 2, 8, 3, 2, 1, 5, 1, 4};
static const float iso_tree_24_threshold[] = {0.0912099183f, 0.982236683f, -2.0f, -2.0f, -0.00377638056f, -0.047829207f, 0.232834026f, -2.0f, -2.0f, 1.38925827f, -2.0f, -2.0f, 2.0109365f, 0.108504288f, -2.0f, -2.0f, 0.010549577f, -2.0f, -2.0f};
static const int iso_tree_24_nodes = 19;

static const int iso_tree_25_left[] = {1, 2, 3, -1, 5, -1, -1, 8, 9, -1, -1, 12, -1, -1, 15, -1, -1};
static const int iso_tree_25_right[] = {14, 7, 4, -1, 6, -1, -1, 11, 10, -1, -1, 13, -1, -1, 16, -1, -1};
static const int iso_tree_25_feature[] = {1, 12, 3, -2, 2, -2, -2, 5, 2, -2, -2, 7, -2, -2, 1, -2, -2};
static const int iso_tree_25_samples[] = {15, 13, 8, 1, 7, 4, 3, 5, 2, 1, 1, 3, 2, 1, 2, 1, 1};
static const float iso_tree_25_threshold[] = {0.0164140537f, 18.08041f, 0.09205167f, -2.0f, 0.980053484f, -2.0f, -2.0f, 9.79739189f, 0.982149124f, -2.0f, -2.0f, 0.528470516f, -2.0f, -2.0f, 0.0178114492f, -2.0f, -2.0f};
static const int iso_tree_25_nodes = 17;

static const int iso_tree_26_left[] = {1, 2, 3, 4, -1, -1, 7, -1, -1, 10, -1, 12, -1, -1, 15, 16, -1, -1, -1};
static const int iso_tree_26_right[] = {14, 9, 6, 5, -1, -1, 8, -1, -1, 11, -1, 13, -1, -1, 18, 17, -1, -1, -1};
static const int iso_tree_26_feature[] = {4, 5, 10, 1, -2, -2, 3, -2, -2, 5, -2, 7, -2, -2, 9, 8, -2, -2, -2};
static const int iso_tree_26_samples[] = {15, 12, 8, 5, 2, 3, 3, 1, 2, 4, 1, 3, 2, 1, 3, 2, 1, 1, 1};
static const float iso_tree_26_threshold[] = {0.051639691f, 9.81488514f, 1.43824685f, 0.0114713367f, -2.0f, -2.0f, 0.0891451761f, -2.0f, -2.0f, 9.81533241f, -2.0f, 0.0241204556f, -2.0f, -2.0f, 0.423919499f, 0.255047411f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_26_nodes = 19;

static const int iso_tree_27_left[] = {1, 2, 3, -1, -1, 6, -1, -1, 9, 10, 11, -1, -1, 14, -1, -1, 17, -1, -1};
static const int iso_tree_27_right[] = {8, 5, 4, -1, -1, 7, -1, -1, 16, 13, 12, -1, -1, 15, -1, -1, 18, -1, -1};
static const int iso_tree_27_feature[] = {3, 2, 6, -2, -2, 12, -2, -2, 11, 7, 3, -2, -2, 12, -2, -2, 0, -2, -2};
static const int iso_tree_27_samples[] = {15, 4, 2, 1, 1, 2, 1, 1, 11, 9, 3, 2, 1, 6, 3, 3, 2, 1, 1};
static const float iso_tree_27_threshold[] = {0.0951858163f, 0.980286002f, 9.82113934f, -2.0f, -2.0f, 18.0576153f, -2.0f, -2.0f, 2.21478653f, 0.602102339f, 0.0985892564f, -2.0f, -2.0f, 17.9694958f, -2.0f, -2.0f, 0.0130557241f, -2.0f, -2.0f};
static const int iso_tree_27_nodes = 19;

static const int iso_tree_28_left[] = {1, 2, 3, -1, 5, -1, -1, -1, 9, 10, 11, -1, -1, 14, -1, -1, 17, -1, -1};
static const int iso_tree_28_right[] = {8, 7, 4, -1, 6, -1, -1, -1, 16, 13, 12, -1, -1, 15, -1, -1, 18, -1, -1};
static const int iso_tree_28_feature[] = {0, 1, 1, -2, 11, -2, -2, -2, 11, 6, 9, -2, -2, 6, -2, -2, 6, -2, -2};
static const int iso_tree_28_samples[] = {15, 8, 7, 1, 6, 4, 2, 1, 7, 5, 2, 1, 1, 3, 2, 1, 2, 1, 1};
static const float iso_tree_28_threshold[] = {0.0125524551f, 0.0162607431f, 0.0106710857f, -2.0f, 2.17657757f, -2.0f, -2.0f, -2.0f, 2.25543571f, 9.80870724f, -0.0495606586f, -2.0f, -2.0f, 9.82237625f, -2.0f, -2.0f, 9.80037308f, -2.0f, -2.0f};
static const int iso_tree_28_nodes = 19;

static const int iso_tree_29_left[] = {1, 2, 3, 4, -1, -1, 7, -1, -1, 10, 11, -1, -1, -1, -1};
static const int iso_tree_29_right[] = {14, 9, 6, 5, -1, -1, 8, -1, -1, 13, 12, -1, -1, -1, -1};
static const int iso_tree_29_feature[] = {0, 10, 5, 5, -2, -2, 8, -2, -2, 5, 0, -2, -2, -2, -2};
static const int iso_tree_29_samples[] = {15, 14, 11, 3, 1, 2, 8, 4, 4, 3, 2, 1, 1, 1, 1};
static const float iso_tree_29_threshold[] = {0.0158290602f, 1.58697701f, 9.79548836f, 9.7934227f, -2.0f, -2.0f, 0.790466845f, -2.0f, -2.0f, 9.82455635f, 0.0115480218f, -2.0f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_29_nodes = 15;

static const int iso_tree_30_left[] = {1, 2, 3, -1, 5, -1, -1, 8, 9, -1, -1, 12, -1, -1, 15, -1, 17, -1, -1};
static const int iso_tree_30_right[] = {14, 7, 4, -1, 6, -1, -1, 11, 10, -1, -1, 13, -1, -1, 16, -1, 18, -1, -1};
static const int iso_tree_30_feature[] = {10, 11, 5, -2, 12, -2, -2, 6, 1, -2, -2, 6, -2, -2, 12, -2, 4, -2, -2};
static const int iso_tree_30_samples[] = {15, 12, 3, 1, 2, 1, 1, 9, 2, 1, 1, 7, 5, 2, 3, 1, 2, 1, 1};
static const float iso_tree_30_threshold[] = {1.52670336f, 2.00192833f, 9.80218506f, -2.0f, 17.9784355f, -2.0f, -2.0f, 9.79872799f, 0.0129031194f, -2.0f, -2.0f, 9.81054115f, -2.0f, -2.0f, 17.9635658f, -2.0f, -0.0380950272f, -2.0f, -2.0f};
static const int iso_tree_30_nodes = 19;

static const int iso_tree_31_left[] = {1, -1, 3, 4, -1, -1, 7, 8, -1, -1, -1};
static const int iso_tree_31_right[] = {2, -1, 6, 5, -1, -1, 10, 9, -1, -1, -1};
static const int iso_tree_31_feature[] = {5, -2, 10, 2, -2, -2, 4, 7, -2, -2, -2};
static const int iso_tree_31_samples[] = {15, 1, 14, 2, 1, 1, 12, 11, 5, 6, 1};
static const float iso_tree_31_threshold[] = {9.79038429f, -2.0f, 1.39732742f, 0.980749965f, -2.0f, -2.0f, 0.0574136414f, 0.140142843f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_31_nodes = 11;

static const int iso_tree_32_left[] = {1, 2, 3, 4, -1, -1, 7, -1, -1, 10, 11, -1, -1, 14, -1, -1, 17, -1, -1};
static const int iso_tree_32_right[] = {16, 9, 6, 5, -1, -1, 8, -1, -1, 13, 12, -1, -1, 15, -1, -1, 18, -1, -1};
static const int iso_tree_32_feature[] = {9, 10, 8, 5, -2, -2, 5, -2, -2, 6, 11, -2, -2, 8, -2, -2, 0, -2, -2};
static const int iso_tree_32_samples[] = {15, 13, 6, 4, 1, 3, 2, 1, 1, 7, 2, 1, 1, 5, 3, 2, 2, 1, 1};
static const float iso_tree_32_threshold[] = {0.435741335f, 1.49702954f, 1.21823859f, 9.79617214f, -2.0f, -2.0f, 9.81401253f, -2.0f, -2.0f, 9.80827236f, 2.02105784f, -2.0f, -2.0f, 0.0823926479f, -2.0f, -2.0f, 0.00991605222f, -2.0f, -2.0f};
static const int iso_tree_32_nodes = 19;

static const int iso_tree_33_left[] = {1, 2, -1, 4, -1, 6, -1, -1, 9, 10, 11, -1, -1, 14, -1, -1, 17, 18, -1, -1, -1};
static const int iso_tree_33_right[] = {8, 3, -1, 5, -1, 7, -1, -1, 16, 13, 12, -1, -1, 15, -1, -1, 20, 19, -1, -1, -1};
static const int iso_tree_33_feature[] = {9, 0, -2, 3, -2, 6, -2, -2, 0, 4, 10, -2, -2, 1, -2, -2, 0, 7, -2, -2, -2};
static const int iso_tree_33_samples[] = {15, 5, 1, 4, 1, 3, 2, 1, 10, 5, 2, 1, 1, 3, 1, 2, 5, 4, 2, 2, 1};
static const float iso_tree_33_threshold[] = {-0.107700408f, 0.010232674f, -2.0f, 0.0951206982f, -2.0f, 9.81187248f, -2.0f, -2.0f, 0.0118821952f, 0.0128971012f, 1.52762187f, -2.0f, -2.0f, 0.0143017787f, -2.0f, -2.0f, 0.015257407f, -0.661468208f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_33_nodes = 21;

static const int iso_tree_34_left[] = {1, 2, 3, 4, -1, -1, -1, 8, -1, 10, -1, -1, 13, 14, 15, -1, -1, -1, 19, 20, -1, -1, -1};
static const int iso_tree_34_right[] = {12, 7, 6, 5, -1, -1, -1, 9, -1, 11, -1, -1, 18, 17, 16, -1, -1, -1, 22, 21, -1, -1, -1};
static const int iso_tree_34_feature[] = {1, 8, 1, 3, -2, -2, -2, 9, -2, 5, -2, -2, 0, 10, 4, -2, -2, -2, 0, 10, -2, -2, -2};
static const int iso_tree_34_samples[] = {15, 7, 4, 3, 2, 1, 1, 3, 1, 2, 1, 1, 8, 4, 3, 1, 2, 1, 4, 3, 1, 2, 1};
static const float iso_tree_34_threshold[] = {0.0135292485f, -0.468867421f, 0.0127622848f, 0.105258375f, -2.0f, -2.0f, -2.0f, -0.585072637f, -2.0f, 9.79671669f, -2.0f, -2.0f, 0.012436891f, 1.58039832f, 0.0500641093f, -2.0f, -2.0f, -2.0f, 0.0148936426f, 1.33304584f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_34_nodes = 23;

static const int iso_tree_35_left[] = {1, 2, -1, -1, 5, 6, 7, -1, -1, -1, -1};
static const int iso_tree_35_right[] = {4, 3, -1, -1, 10, 9, 8, -1, -1, -1, -1};
static const int iso_tree_35_feature[] = {9, 7, -2, -2, 4, 3, 6, -2, -2, -2, -2};
static const int iso_tree_35_samples[] = {15, 2, 1, 1, 13, 12, 11, 9, 2, 1, 1};
static const float iso_tree_35_threshold[] = {-0.539756119f, -0.414493203f, -2.0f, -2.0f, 0.0584811345f, 0.107209183f, 9.81714725f, -2.0f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_35_nodes = 11;

static const int iso_tree_36_left[] = {1, 2, -1, -1, 5, 6, 7, -1, -1, 10, -1, -1, 13, 14, -1, -1, 17, -1, -1};
static const int iso_tree_36_right[] = {4, 3, -1, -1, 12, 9, 8, -1, -1, 11, -1, -1, 16, 15, -1, -1, 18, -1, -1};
static const int iso_tree_36_feature[] = {10, 11, -2, -2, 0, 3, 5, -2, -2, 8, -2, -2, 8, 10, -2, -2, 4, -2, -2};
static const int iso_tree_36_samples[] = {15, 2, 1, 1, 13, 4, 2, 1, 1, 2, 1, 1, 9, 3, 2, 1, 6, 2, 4};
static const float iso_tree_36_threshold[] = {1.33647835f, 2.2361064f, -2.0f, -2.0f, 0.0104077933f, 0.101892933f, 9.81305408f, -2.0f, -2.0f, -0.881219804f, -2.0f, -2.0f, 0.239178821f, 1.5511899f, -2.0f, -2.0f, -0.0242049359f, -2.0f, -2.0f};
static const int iso_tree_36_nodes = 19;

static const int iso_tree_37_left[] = {1, 2, -1, 4, 5, -1, -1, 8, -1, -1, 11, 12, -1, 14, -1, -1, -1};
static const int iso_tree_37_right[] = {10, 3, -1, 7, 6, -1, -1, 9, -1, -1, 16, 13, -1, 15, -1, -1, -1};
static const int iso_tree_37_feature[] = {5, 1, -2, 8, 10, -2, -2, 7, -2, -2, 11, 3, -2, 4, -2, -2, -2};
static const int iso_tree_37_samples[] = {15, 6, 1, 5, 3, 1, 2, 2, 1, 1, 9, 8, 1, 7, 1, 6, 1};
static const float iso_tree_37_threshold[] = {9.80277348f, 0.0108495317f, -2.0f, 1.01949179f, 1.40645373f, -2.0f, -2.0f, -0.835947335f, -2.0f, -2.0f, 2.24817133f, 0.0910086185f, -2.0f, -0.0122403111f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_37_nodes = 17;

static const int iso_tree_38_left[] = {1, 2, 3, 4, -1, -1, 7, -1, -1, -1, 11, 12, 13, -1, -1, -1, 17, -1, -1};
static const int iso_tree_38_right[] = {10, 9, 6, 5, -1, -1, 8, -1, -1, -1, 16, 15, 14, -1, -1, -1, 18, -1, -1};
static const int iso_tree_38_feature[] = {4, 11, 4, 1, -2, -2, 7, -2, -2, -2, 8, 6, 3, -2, -2, -2, 1, -2, -2};
static const int iso_tree_38_samples[] = {15, 7, 6, 3, 1, 2, 3, 1, 2, 1, 8, 6, 5, 4, 1, 1, 2, 1, 1};
static const float iso_tree_38_threshold[] = {0.0394084342f, 2.23904371f, -0.0433370955f, 0.0105440645f, -2.0f, -2.0f, -0.498444289f, -2.0f, -2.0f, -2.0f, 1.12160218f, 9.8281002f, 0.104308143f, -2.0f, -2.0f, -2.0f, 0.0164629426f, -2.0f, -2.0f};
static const int iso_tree_38_nodes = 19;

static const int iso_tree_39_left[] = {1, 2, 3, 4, -1, -1, -1, -1, 9, 10, -1, 12, -1, -1, -1};
static const int iso_tree_39_right[] = {8, 7, 6, 5, -1, -1, -1, -1, 14, 11, -1, 13, -1, -1, -1};
static const int iso_tree_39_feature[] = {3, 8, 8, 5, -2, -2, -2, -2, 12, 5, -2, 8, -2, -2, -2};
static const int iso_tree_39_samples[] = {15, 7, 6, 5, 1, 4, 1, 1, 8, 7, 1, 6, 1, 5, 1};
static const float iso_tree_39_threshold[] = {0.0994945988f, 1.28114462f, 0.680671096f, 9.79061508f, -2.0f, -2.0f, -2.0f, -2.0f, 18.1289768f, 9.80314922f, -2.0f, -0.866549492f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_39_nodes = 15;

static const int iso_tree_40_left[] = {1, -1, 3, 4, 5, -1, -1, 8, -1, -1, 11, 12, -1, -1, 15, -1, -1};
static const int iso_tree_40_right[] = {2, -1, 10, 7, 6, -1, -1, 9, -1, -1, 14, 13, -1, -1, 16, -1, -1};
static const int iso_tree_40_feature[] = {8, -2, 4, 12, 8, -2, -2, 1, -2, -2, 3, 3, -2, -2, 5, -2, -2};
static const int iso_tree_40_samples[] = {15, 1, 14, 6, 3, 1, 2, 3, 2, 1, 8, 5, 1, 4, 3, 1, 2};
static const float iso_tree_40_threshold[] = {-0.921189547f, -2.0f, 0.00315055647f, 18.0480881f, 0.407105476f, -2.0f, -2.0f, 0.0154027892f, -2.0f, -2.0f, 0.105942033f, 0.101161741f, -2.0f, -2.0f, 9.81290817f, -2.0f, -2.0f};
static const int iso_tree_40_nodes = 17;

static const int iso_tree_41_left[] = {1, 2, 3, 4, -1, -1, 7, -1, -1, -1, 11, 12, 13, -1, -1, 16, -1, -1, 19, -1, -1};
static const int iso_tree_41_right[] = {10, 9, 6, 5, -1, -1, 8, -1, -1, -1, 18, 15, 14, -1, -1, 17, -1, -1, 20, -1, -1};
static const int iso_tree_41_feature[] = {6, 8, 8, 5, -2, -2, 11, -2, -2, -2, 7, 4, 2, -2, -2, 8, -2, -2, 7, -2, -2};
static const int iso_tree_41_samples[] = {15, 8, 7, 4, 2, 2, 3, 1, 2, 1, 7, 5, 2, 1, 1, 3, 1, 2, 2, 1, 1};
static const float iso_tree_41_threshold[] = {9.81041908f, 1.25423932f, 0.870105803f, 9.79800415f, -2.0f, -2.0f, 2.19134855f, -2.0f, -2.0f, -2.0f, 1.28971529f, 0.0295846891f, 0.977657318f, -2.0f, -2.0f, 0.589545727f, -2.0f, -2.0f, 1.47503245f, -2.0f, -2.0f};
static const int iso_tree_41_nodes = 21;

static const int iso_tree_42_left[] = {1, 2, -1, 4, 5, -1, -1, 8, -1, -1, 11, 12, 13, -1, -1, -1, 17, -1, -1};
static const int iso_tree_42_right[] = {10, 3, -1, 7, 6, -1, -1, 9, -1, -1, 16, 15, 14, -1, -1, -1, 18, -1, -1};
static const int iso_tree_42_feature[] = {2, 5, -2, 8, 0, -2, -2, 9, -2, -2, 10, 7, 6, -2, -2, -2, 3, -2, -2};
static const int iso_tree_42_samples[] = {15, 9, 1, 8, 4, 2, 2, 4, 2, 2, 6, 4, 3, 2, 1, 1, 2, 1, 1};
static const float iso_tree_42_threshold[] = {0.981363773f, 9.79683971f, -2.0f, 0.170080408f, 0.0117722675f, -2.0f, -2.0f, -0.149026379f, -2.0f, -2.0f, 1.43115318f, 0.643046558f, 9.80205441f, -2.0f, -2.0f, -2.0f, 0.09419927f, -2.0f, -2.0f};
static const int iso_tree_42_nodes = 19;

static const int iso_tree_43_left[] = {1, 2, 3, 4, -1, -1, 7, -1, -1, 10, 11, -1, -1, 14, -1, -1, 17, 18, -1, -1, -1};
static const int iso_tree_43_right[] = {16, 9, 6, 5, -1, -1, 8, -1, -1, 13, 12, -1, -1, 15, -1, -1, 20, 19, -1, -1, -1};
static const int iso_tree_43_feature[] = {10, 10, 10, 7, -2, -2, 1, -2, -2, 5, 1, -2, -2, 8, -2, -2, 9, 5, -2, -2, -2};
static const int iso_tree_43_samples[] = {15, 12, 6, 2, 1, 1, 4, 1, 3, 6, 4, 2, 2, 2, 1, 1, 3, 2, 1, 1, 1};
static const float iso_tree_43_threshold[] = {1.55200684f, 1.43331444f, 1.30094612f, -0.696437836f, -2.0f, -2.0f, 0.0115722725f, -2.0f, -2.0f, 9.81122017f, 0.0134277698f, -2.0f, -2.0f, 0.505485415f, -2.0f, -2.0f, 0.415384769f, 9.82374001f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_43_nodes = 21;

static const int iso_tree_44_left[] = {1, 2, 3, -1, 5, -1, -1, 8, 9, -1, -1, 12, -1, -1, 15, -1, -1};
static const int iso_tree_44_right[] = {14, 7, 4, -1, 6, -1, -1, 11, 10, -1, -1, 13, -1, -1, 16, -1, -1};
static const int iso_tree_44_feature[] = {12, 5, 8, -2, 4, -2, -2, 8, 6, -2, -2, 11, -2, -2, 1, -2, -2};
static const int iso_tree_44_samples[] = {15, 13, 4, 1, 3, 2, 1, 9, 3, 2, 1, 6, 5, 1, 2, 1, 1};
static const float iso_tree_44_threshold[] = {18.1841393f, 9.79838657f, 0.244701266f, -2.0f, -0.0459615663f, -2.0f, -2.0f, -0.172102213f, 9.82786179f, -2.0f, -2.0f, 2.11791253f, -2.0f, -2.0f, 0.0137735503f, -2.0f, -2.0f};
static const int iso_tree_44_nodes = 17;

static const int iso_tree_45_left[] = {1, 2, 3, 4, -1, -1, 7, -1, -1, 10, 11, -1, -1, -1, 15, 16, -1, -1, -1};
static const int iso_tree_45_right[] = {14, 9, 6, 5, -1, -1, 8, -1, -1, 13, 12, -1, -1, -1, 18, 17, -1, -1, -1};
static const int iso_tree_45_feature[] = {6, 9, 6, 2, -2, -2, 0, -2, -2, 9, 7, -2, -2, -2, 12, 1, -2, -2, -2};
static const int iso_tree_45_samples[] = {15, 12, 7, 3, 2, 1, 4, 2, 2, 5, 4, 2, 2, 1, 3, 2, 1, 1, 1};
static const float iso_tree_45_threshold[] = {9.82087231f, 0.186164752f, 9.80423737f, 0.983747065f, -2.0f, -2.0f, 0.0134711908f, -2.0f, -2.0f, 0.461917967f, -0.0649833679f, -2.0f, -2.0f, -2.0f, 18.0042477f, 0.0130630638f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_45_nodes = 19;

static const int iso_tree_46_left[] = {1, 2, 3, 4, -1, -1, 7, -1, -1, -1, 11, 12, -1, -1, 15, 16, -1, -1, 19, -1, -1};
static const int iso_tree_46_right[] = {10, 9, 6, 5, -1, -1, 8, -1, -1, -1, 14, 13, -1, -1, 18, 17, -1, -1, 20, -1, -1};
static const int iso_tree_46_feature[] = {11, 12, 5, 2, -2, -2, 3, -2, -2, -2, 12, 4, -2, -2, 7, 1, -2, -2, 12, -2, -2};
static const int iso_tree_46_samples[] = {15, 5, 4, 2, 1, 1, 2, 1, 1, 1, 10, 2, 1, 1, 8, 5, 3, 2, 3, 2, 1};
static const float iso_tree_46_threshold[] = {2.02673173f, 18.0936127f, 9.82106209f, 0.98376596f, -2.0f, -2.0f, 0.107194752f, -2.0f, -2.0f, -2.0f, 17.9169025f, 0.0401265658f, -2.0f, -2.0f, -0.251420796f, 0.0122894002f, -2.0f, -2.0f, 18.0506096f, -2.0f, -2.0f};
static const int iso_tree_46_nodes = 21;

static const int iso_tree_47_left[] = {1, 2, 3, -1, -1, 6, -1, -1, 9, 10, -1, 12, -1, -1, 15, 16, -1, -1, 19, -1, -1};
static const int iso_tree_47_right[] = {8, 5, 4, -1, -1, 7, -1, -1, 14, 11, -1, 13, -1, -1, 18, 17, -1, -1, 20, -1, -1};
static const int iso_tree_47_feature[] = {12, 2, 1, -2, -2, 5, -2, -2, 3, 7, -2, 4, -2, -2, 3, 3, -2, -2, 7, -2, -2};
static const int iso_tree_47_samples[] = {15, 4, 2, 1, 1, 2, 1, 1, 11, 3, 1, 2, 1, 1, 8, 6, 4, 2, 2, 1, 1};
static const float iso_tree_47_threshold[] = {17.9370995f, 0.980694294f, 0.0123400157f, -2.0f, -2.0f, 9.80540371f, -2.0f, -2.0f, 0.0926233977f, -0.465849072f, -2.0f, -0.0398801006f, -2.0f, -2.0f, 0.10478048f, 0.100862123f, -2.0f, -2.0f, 1.33159554f, -2.0f, -2.0f};
static const int iso_tree_47_nodes = 21;

static const int iso_tree_48_left[] = {1, 2, 3, 4, -1, -1, 7, -1, -1, -1, 11, 12, 13, -1, -1, -1, -1};
static const int iso_tree_48_right[] = {10, 9, 6, 5, -1, -1, 8, -1, -1, -1, 16, 15, 14, -1, -1, -1, -1};
static const int iso_tree_48_feature[] = {4, 1, 5, 2, -2, -2, 12, -2, -2, -2, 8, 11, 0, -2, -2, -2, -2};
static const int iso_tree_48_samples[] = {15, 6, 5, 2, 1, 1, 3, 1, 2, 1, 9, 8, 7, 3, 4, 1, 1};
static const float iso_tree_48_threshold[] = {-0.0371025428f, 0.0143269747f, 9.7966404f, 0.981643081f, -2.0f, -2.0f, 18.0965576f, -2.0f, -2.0f, -2.0f, 1.38922203f, 2.10912561f, 0.0112534901f, -2.0f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_48_nodes = 17;

static const int iso_tree_49_left[] = {1, 2, 3, 4, -1, -1, -1, 8, -1, -1, 11, 12, -1, 14, -1, -1, 17, 18, -1, -1, -1};
static const int iso_tree_49_right[] = {10, 7, 6, 5, -1, -1, -1, 9, -1, -1, 16, 13, -1, 15, -1, -1, 20, 19, -1, -1, -1};
static const int iso_tree_49_feature[] = {2, 3, 9, 3, -2, -2, -2, 8, -2, -2, 11, 11, -2, 4, -2, -2, 2, 7, -2, -2, -2};
static const int iso_tree_49_samples[] = {15, 7, 5, 4, 1, 3, 1, 2, 1, 1, 8, 4, 1, 3, 1, 2, 4, 3, 2, 1, 1};
static const float iso_tree_49_threshold[] = {0.980279863f, 0.10464333f, 0.426321596f, 0.0950015783f, -2.0f, -2.0f, -2.0f, -0.865353584f, -2.0f, -2.0f, 2.10558581f, 2.09649873f, -2.0f, 0.00158368156f, -2.0f, -2.0f, 0.982522905f, 0.910404801f, -2.0f, -2.0f, -2.0f};
static const int iso_tree_49_nodes = 21;

static inline float isolation_forest_score_samples(const float *features) {
    float total_depth = 0.0f;
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_0_left[node] != -1) {
            int feature = iso_tree_0_feature[node];
            node = features[feature] <= iso_tree_0_threshold[node] ? iso_tree_0_left[node] : iso_tree_0_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_0_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_1_left[node] != -1) {
            int feature = iso_tree_1_feature[node];
            node = features[feature] <= iso_tree_1_threshold[node] ? iso_tree_1_left[node] : iso_tree_1_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_1_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_2_left[node] != -1) {
            int feature = iso_tree_2_feature[node];
            node = features[feature] <= iso_tree_2_threshold[node] ? iso_tree_2_left[node] : iso_tree_2_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_2_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_3_left[node] != -1) {
            int feature = iso_tree_3_feature[node];
            node = features[feature] <= iso_tree_3_threshold[node] ? iso_tree_3_left[node] : iso_tree_3_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_3_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_4_left[node] != -1) {
            int feature = iso_tree_4_feature[node];
            node = features[feature] <= iso_tree_4_threshold[node] ? iso_tree_4_left[node] : iso_tree_4_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_4_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_5_left[node] != -1) {
            int feature = iso_tree_5_feature[node];
            node = features[feature] <= iso_tree_5_threshold[node] ? iso_tree_5_left[node] : iso_tree_5_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_5_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_6_left[node] != -1) {
            int feature = iso_tree_6_feature[node];
            node = features[feature] <= iso_tree_6_threshold[node] ? iso_tree_6_left[node] : iso_tree_6_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_6_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_7_left[node] != -1) {
            int feature = iso_tree_7_feature[node];
            node = features[feature] <= iso_tree_7_threshold[node] ? iso_tree_7_left[node] : iso_tree_7_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_7_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_8_left[node] != -1) {
            int feature = iso_tree_8_feature[node];
            node = features[feature] <= iso_tree_8_threshold[node] ? iso_tree_8_left[node] : iso_tree_8_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_8_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_9_left[node] != -1) {
            int feature = iso_tree_9_feature[node];
            node = features[feature] <= iso_tree_9_threshold[node] ? iso_tree_9_left[node] : iso_tree_9_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_9_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_10_left[node] != -1) {
            int feature = iso_tree_10_feature[node];
            node = features[feature] <= iso_tree_10_threshold[node] ? iso_tree_10_left[node] : iso_tree_10_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_10_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_11_left[node] != -1) {
            int feature = iso_tree_11_feature[node];
            node = features[feature] <= iso_tree_11_threshold[node] ? iso_tree_11_left[node] : iso_tree_11_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_11_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_12_left[node] != -1) {
            int feature = iso_tree_12_feature[node];
            node = features[feature] <= iso_tree_12_threshold[node] ? iso_tree_12_left[node] : iso_tree_12_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_12_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_13_left[node] != -1) {
            int feature = iso_tree_13_feature[node];
            node = features[feature] <= iso_tree_13_threshold[node] ? iso_tree_13_left[node] : iso_tree_13_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_13_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_14_left[node] != -1) {
            int feature = iso_tree_14_feature[node];
            node = features[feature] <= iso_tree_14_threshold[node] ? iso_tree_14_left[node] : iso_tree_14_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_14_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_15_left[node] != -1) {
            int feature = iso_tree_15_feature[node];
            node = features[feature] <= iso_tree_15_threshold[node] ? iso_tree_15_left[node] : iso_tree_15_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_15_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_16_left[node] != -1) {
            int feature = iso_tree_16_feature[node];
            node = features[feature] <= iso_tree_16_threshold[node] ? iso_tree_16_left[node] : iso_tree_16_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_16_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_17_left[node] != -1) {
            int feature = iso_tree_17_feature[node];
            node = features[feature] <= iso_tree_17_threshold[node] ? iso_tree_17_left[node] : iso_tree_17_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_17_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_18_left[node] != -1) {
            int feature = iso_tree_18_feature[node];
            node = features[feature] <= iso_tree_18_threshold[node] ? iso_tree_18_left[node] : iso_tree_18_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_18_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_19_left[node] != -1) {
            int feature = iso_tree_19_feature[node];
            node = features[feature] <= iso_tree_19_threshold[node] ? iso_tree_19_left[node] : iso_tree_19_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_19_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_20_left[node] != -1) {
            int feature = iso_tree_20_feature[node];
            node = features[feature] <= iso_tree_20_threshold[node] ? iso_tree_20_left[node] : iso_tree_20_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_20_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_21_left[node] != -1) {
            int feature = iso_tree_21_feature[node];
            node = features[feature] <= iso_tree_21_threshold[node] ? iso_tree_21_left[node] : iso_tree_21_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_21_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_22_left[node] != -1) {
            int feature = iso_tree_22_feature[node];
            node = features[feature] <= iso_tree_22_threshold[node] ? iso_tree_22_left[node] : iso_tree_22_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_22_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_23_left[node] != -1) {
            int feature = iso_tree_23_feature[node];
            node = features[feature] <= iso_tree_23_threshold[node] ? iso_tree_23_left[node] : iso_tree_23_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_23_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_24_left[node] != -1) {
            int feature = iso_tree_24_feature[node];
            node = features[feature] <= iso_tree_24_threshold[node] ? iso_tree_24_left[node] : iso_tree_24_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_24_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_25_left[node] != -1) {
            int feature = iso_tree_25_feature[node];
            node = features[feature] <= iso_tree_25_threshold[node] ? iso_tree_25_left[node] : iso_tree_25_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_25_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_26_left[node] != -1) {
            int feature = iso_tree_26_feature[node];
            node = features[feature] <= iso_tree_26_threshold[node] ? iso_tree_26_left[node] : iso_tree_26_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_26_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_27_left[node] != -1) {
            int feature = iso_tree_27_feature[node];
            node = features[feature] <= iso_tree_27_threshold[node] ? iso_tree_27_left[node] : iso_tree_27_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_27_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_28_left[node] != -1) {
            int feature = iso_tree_28_feature[node];
            node = features[feature] <= iso_tree_28_threshold[node] ? iso_tree_28_left[node] : iso_tree_28_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_28_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_29_left[node] != -1) {
            int feature = iso_tree_29_feature[node];
            node = features[feature] <= iso_tree_29_threshold[node] ? iso_tree_29_left[node] : iso_tree_29_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_29_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_30_left[node] != -1) {
            int feature = iso_tree_30_feature[node];
            node = features[feature] <= iso_tree_30_threshold[node] ? iso_tree_30_left[node] : iso_tree_30_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_30_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_31_left[node] != -1) {
            int feature = iso_tree_31_feature[node];
            node = features[feature] <= iso_tree_31_threshold[node] ? iso_tree_31_left[node] : iso_tree_31_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_31_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_32_left[node] != -1) {
            int feature = iso_tree_32_feature[node];
            node = features[feature] <= iso_tree_32_threshold[node] ? iso_tree_32_left[node] : iso_tree_32_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_32_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_33_left[node] != -1) {
            int feature = iso_tree_33_feature[node];
            node = features[feature] <= iso_tree_33_threshold[node] ? iso_tree_33_left[node] : iso_tree_33_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_33_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_34_left[node] != -1) {
            int feature = iso_tree_34_feature[node];
            node = features[feature] <= iso_tree_34_threshold[node] ? iso_tree_34_left[node] : iso_tree_34_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_34_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_35_left[node] != -1) {
            int feature = iso_tree_35_feature[node];
            node = features[feature] <= iso_tree_35_threshold[node] ? iso_tree_35_left[node] : iso_tree_35_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_35_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_36_left[node] != -1) {
            int feature = iso_tree_36_feature[node];
            node = features[feature] <= iso_tree_36_threshold[node] ? iso_tree_36_left[node] : iso_tree_36_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_36_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_37_left[node] != -1) {
            int feature = iso_tree_37_feature[node];
            node = features[feature] <= iso_tree_37_threshold[node] ? iso_tree_37_left[node] : iso_tree_37_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_37_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_38_left[node] != -1) {
            int feature = iso_tree_38_feature[node];
            node = features[feature] <= iso_tree_38_threshold[node] ? iso_tree_38_left[node] : iso_tree_38_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_38_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_39_left[node] != -1) {
            int feature = iso_tree_39_feature[node];
            node = features[feature] <= iso_tree_39_threshold[node] ? iso_tree_39_left[node] : iso_tree_39_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_39_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_40_left[node] != -1) {
            int feature = iso_tree_40_feature[node];
            node = features[feature] <= iso_tree_40_threshold[node] ? iso_tree_40_left[node] : iso_tree_40_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_40_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_41_left[node] != -1) {
            int feature = iso_tree_41_feature[node];
            node = features[feature] <= iso_tree_41_threshold[node] ? iso_tree_41_left[node] : iso_tree_41_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_41_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_42_left[node] != -1) {
            int feature = iso_tree_42_feature[node];
            node = features[feature] <= iso_tree_42_threshold[node] ? iso_tree_42_left[node] : iso_tree_42_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_42_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_43_left[node] != -1) {
            int feature = iso_tree_43_feature[node];
            node = features[feature] <= iso_tree_43_threshold[node] ? iso_tree_43_left[node] : iso_tree_43_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_43_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_44_left[node] != -1) {
            int feature = iso_tree_44_feature[node];
            node = features[feature] <= iso_tree_44_threshold[node] ? iso_tree_44_left[node] : iso_tree_44_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_44_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_45_left[node] != -1) {
            int feature = iso_tree_45_feature[node];
            node = features[feature] <= iso_tree_45_threshold[node] ? iso_tree_45_left[node] : iso_tree_45_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_45_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_46_left[node] != -1) {
            int feature = iso_tree_46_feature[node];
            node = features[feature] <= iso_tree_46_threshold[node] ? iso_tree_46_left[node] : iso_tree_46_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_46_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_47_left[node] != -1) {
            int feature = iso_tree_47_feature[node];
            node = features[feature] <= iso_tree_47_threshold[node] ? iso_tree_47_left[node] : iso_tree_47_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_47_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_48_left[node] != -1) {
            int feature = iso_tree_48_feature[node];
            node = features[feature] <= iso_tree_48_threshold[node] ? iso_tree_48_left[node] : iso_tree_48_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_48_samples[node]);
    }
    {
        int node = 0;
        int depth = 0;
        while (iso_tree_49_left[node] != -1) {
            int feature = iso_tree_49_feature[node];
            node = features[feature] <= iso_tree_49_threshold[node] ? iso_tree_49_left[node] : iso_tree_49_right[node];
            depth++;
        }
        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_49_samples[node]);
    }
    return -powf(2.0f, -total_depth / 228.293961f);
}

static inline float isolation_forest_decision_function(const float *features) {
    return isolation_forest_score_samples(features) - -0.567642152f;
}

// Predict: 1 for normal (inlier), -1 for anomaly (outlier)
static inline int isolation_forest_predict(const float *features) {
    return isolation_forest_decision_function(features) >= 0.0f ? 1 : -1;
}

// Compatibility aliases
static inline float anomaly_model_score_samples(const float *features) {
    return isolation_forest_score_samples(features);
}

static inline float anomaly_model_decision_function(const float *features) {
    return isolation_forest_decision_function(features);
}

#endif // ISOLATION_FOREST_H
