#ifndef ISOLATION_FOREST_WRAPPER_H
#define ISOLATION_FOREST_WRAPPER_H

// 1. Include the header generated by train_iso_forest.py
#include "Isolation_Forest.h" 
#include "LoRa_Packetizer.h"

// 2. Convert SensorPacket to a float feature array matching FEATURES in Python
static inline void toFeatureVector(const SensorPacket& packet, float* out) {
    out[0]  = (float)packet.displacementX_mm / 1000.0f;
    out[1]  = (float)packet.displacementY_mm / 1000.0f;
    out[2]  = (float)packet.displacementZ_mm / 1000.0f;
    out[3]  = (float)packet.accX_mmss2        / 1000.0f;
    out[4]  = (float)packet.accY_mmss2        / 1000.0f;
    out[5]  = (float)packet.accZ_mmss2        / 1000.0f;
    out[6]  = (float)packet.resultantAccel   / 1000.0f;
    out[7]  = (float)packet.rateRollDegS     / 10.0f;
    out[8]  = (float)packet.ratePitchDegS    / 10.0f;
    out[9]  = (float)packet.rateYawDegS      / 10.0f;
    out[10] = (float)packet.angleRoll        / 10.0f;
    out[11] = (float)packet.anglePitch       / 10.0f;
    out[12] = (float)packet.angleYaw         / 10.0f;
    out[13] = (float)packet.vibrationDetected;
    out[14] = (float)packet.isHighPrecision;
}

// 3. Wrapper functions called by main.cpp
static inline float iforestScore(const SensorPacket& p) {
    float features[ISOLATION_FOREST_N_FEATURES];
    toFeatureVector(p, features);
    return isolation_forest_decision_function(features);
}

static inline int iforestPredict(const SensorPacket& p) {
    float features[ISOLATION_FOREST_N_FEATURES];
    toFeatureVector(p, features);
    return isolation_forest_predict(features);
}

#endif // ISOLATION_FOREST_WRAPPER_H