#!/usr/bin/env python3
"""
Train an IsolationForest on SensorPacket logs and export it as a C header
(isolation_forest.h) for the ESP32.

The 14-feature layout and unit conversions here MUST match toFeatureVector()
in isolation_forest_data.h. If you change one, change the other.

Usage:
    python tools/Train_Isolation_Forest.py data/normal_log.csv -o include/Isolation_Forest.h
    python tools/Train_Isolation_Forest.py data/normal_log.csv --contamination 0.01 --verify

CSV columns (raw SensorPacket field names, integer-scaled units as sent):
    displacementX_mm, displacementY_mm, displacementZ_mm,
    accX_mmss2, accY_mmss2, accZ_mmss2, resultantAccel,
    rateRollDegS, ratePitchDegS, rateYawDegS,
    angleRoll, anglePitch, angleYaw, vibrationDetected

Train on NORMAL operation data. Isolation Forest is unsupervised: whatever is
common in the training set is what the device will treat as "normal".
"""

"""
command for running py file:
python tools/Train_Isolation_Forest.py data/normal_log.csv -o include/Isolation_Forest.h --verify
"""

import argparse
import sys

import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest

# (csv_column, divisor) in the exact order the firmware feeds the model.
FEATURES = [
    ("displacementX_mm", 1000.0),  # 0  -> m
    ("displacementY_mm", 1000.0),  # 1  -> m
    ("displacementZ_mm", 1000.0),  # 2  -> m
    ("accX_mmss2",       1000.0),  # 3  -> m/s^2
    ("accY_mmss2",       1000.0),  # 4  -> m/s^2
    ("accZ_mmss2",       1000.0),  # 5  -> m/s^2
    ("resultantAccel",   1000.0),  # 6  -> m/s^2
    ("rateRollDegS",       10.0),  # 7  -> deg/s
    ("ratePitchDegS",      10.0),  # 8  -> deg/s
    ("rateYawDegS",        10.0),  # 9  -> deg/s
    ("angleRoll",          10.0),  # 10 -> deg
    ("anglePitch",         10.0),  # 11 -> deg
    ("angleYaw",           10.0),  # 12 -> deg
    ("vibrationDetected",   1.0),  # 13 -> 0/1
    ("isHighPrecision",   1.0),  # 14 -> 0/1
    
]
N_FEATURES = len(FEATURES)


def load_features(path, already_scaled=False):
    df = pd.read_csv(path)
    missing = [c for c, _ in FEATURES if c not in df.columns]
    if missing:
        sys.exit(f"CSV is missing columns: {missing}")
    X = df[[c for c, _ in FEATURES]].astype(np.float64).to_numpy()
    if not already_scaled:
        X = X / np.array([d for _, d in FEATURES])
    mask = np.isfinite(X).all(axis=1)
    if not mask.all():
        print(f"Dropping {(~mask).sum()} rows with NaN/inf", file=sys.stderr)
    return X[mask].astype(np.float32)  # firmware compares in float32


def avg_path_length(n):
    """Same formula as isolation_forest_average_path_length() in the header."""
    if n <= 1:
        return 0.0
    if n == 2:
        return 1.0
    return 2.0 * (np.log(n - 1.0) + 0.5772156649) - 2.0 * (n - 1.0) / n


def fmt_f(x):
    s = "%.9g" % float(np.float32(x))
    if "e" not in s and "." not in s and "inf" not in s and "nan" not in s:
        s += ".0"
    return s + "f"


def export_header(clf, out_path, source_name):
    n_trees = len(clf.estimators_)
    c_norm = n_trees * avg_path_length(clf.max_samples_)

    L = []
    L.append(f"// Generated by Train_Isolation_Forest.py from {source_name}. Do not edit.")
    L.append("#ifndef ISOLATION_FOREST_H")
    L.append("#define ISOLATION_FOREST_H")
    L.append("")
    L.append("#include <math.h>")
    L.append("")
    L.append("// Input vector layout (must match toFeatureVector() in isolation_forest_data.h):")
    for i, (name, div) in enumerate(FEATURES):
        L.append(f"//   [{i:2d}] {name} / {div:g}")
    L.append(f"#define ISOLATION_FOREST_N_FEATURES {N_FEATURES}")
    L.append("")
    L.append("static inline float isolation_forest_average_path_length(int n_samples) {")
    L.append("    if (n_samples <= 1) return 0.0f;")
    L.append("    if (n_samples == 2) return 1.0f;")
    L.append("    return 2.0f * (logf((float)(n_samples - 1)) + 0.5772156649f) -")
    L.append("           2.0f * (float)(n_samples - 1) / (float)n_samples;")
    L.append("}")
    L.append("")

    for t, (est, feat_idx) in enumerate(zip(clf.estimators_, clf.estimators_features_)):
        tr = est.tree_
        feat_idx = np.asarray(feat_idx)
        # Map each node's feature back to the original column index.
        feats = [int(feat_idx[f]) if f >= 0 else -2 for f in tr.feature]
        L.append(f"static const int iso_tree_{t}_left[] = {{{', '.join(str(int(v)) for v in tr.children_left)}}};")
        L.append(f"static const int iso_tree_{t}_right[] = {{{', '.join(str(int(v)) for v in tr.children_right)}}};")
        L.append(f"static const int iso_tree_{t}_feature[] = {{{', '.join(map(str, feats))}}};")
        L.append(f"static const int iso_tree_{t}_samples[] = {{{', '.join(str(int(v)) for v in tr.n_node_samples)}}};")
        L.append(f"static const float iso_tree_{t}_threshold[] = {{{', '.join(fmt_f(v) for v in tr.threshold)}}};")
        L.append(f"static const int iso_tree_{t}_nodes = {tr.node_count};")
        L.append("")

    L.append("static inline float isolation_forest_score_samples(const float *features) {")
    L.append("    float total_depth = 0.0f;")
    for t in range(n_trees):
        L.append("    {")
        L.append("        int node = 0;")
        L.append("        int depth = 0;")
        L.append(f"        while (iso_tree_{t}_left[node] != -1) {{")
        L.append(f"            int feature = iso_tree_{t}_feature[node];")
        L.append(f"            node = features[feature] <= iso_tree_{t}_threshold[node] ? iso_tree_{t}_left[node] : iso_tree_{t}_right[node];")
        L.append("            depth++;")
        L.append("        }")
        L.append(f"        total_depth += (float)depth + isolation_forest_average_path_length(iso_tree_{t}_samples[node]);")
        L.append("    }")
    L.append(f"    return -powf(2.0f, -total_depth / {fmt_f(c_norm)});")
    L.append("}")
    L.append("")
    L.append("static inline float isolation_forest_decision_function(const float *features) {")
    L.append(f"    return isolation_forest_score_samples(features) - {fmt_f(clf.offset_)};")
    L.append("}")
    L.append("")
    L.append("// Predict: 1 for normal (inlier), -1 for anomaly (outlier)")
    L.append("static inline int isolation_forest_predict(const float *features) {")
    L.append("    return isolation_forest_decision_function(features) >= 0.0f ? 1 : -1;")
    L.append("}")
    L.append("")
    L.append("// Compatibility aliases")
    L.append("static inline float anomaly_model_score_samples(const float *features) {")
    L.append("    return isolation_forest_score_samples(features);")
    L.append("}")
    L.append("")
    L.append("static inline float anomaly_model_decision_function(const float *features) {")
    L.append("    return isolation_forest_decision_function(features);")
    L.append("}")
    L.append("")
    L.append("#endif // ISOLATION_FOREST_H")

    with open(out_path, "w", newline="\n") as f:
        f.write("\n".join(L) + "\n")


def verify_export(clf, X, n=500):
    """Re-implement the exported C traversal in Python and compare with sklearn."""
    idx = np.random.default_rng(0).choice(len(X), size=min(n, len(X)), replace=False)
    c_norm = len(clf.estimators_) * avg_path_length(clf.max_samples_)
    worst = 0.0
    for i in idx:
        x = X[i]
        total = 0.0
        for est, fi in zip(clf.estimators_, clf.estimators_features_):
            tr = est.tree_
            node, depth = 0, 0
            while tr.children_left[node] != -1:
                f = int(np.asarray(fi)[tr.feature[node]])
                thr = np.float32(tr.threshold[node])
                node = tr.children_left[node] if x[f] <= thr else tr.children_right[node]
                depth += 1
            total += depth + avg_path_length(tr.n_node_samples[node])
        mine = -(2.0 ** (-total / c_norm))
        worst = max(worst, abs(mine - clf.score_samples(x[None, :])[0]))
    print(f"verify: max |C-logic - sklearn| over {len(idx)} samples = {worst:.2e}")
    return worst


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("csv", help="CSV of NORMAL-operation SensorPacket rows")
    ap.add_argument("-o", "--out", default="data/Isolation_Forest.h")
    ap.add_argument("--trees", type=int, default=50)
    ap.add_argument("--max-samples", type=int, default=256)
    ap.add_argument("--contamination", type=float, default=0.01,
                    help="expected outlier fraction; sets the decision threshold (default 0.01)")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--already-scaled", action="store_true",
                    help="CSV is already in m, m/s^2, deg/s, deg (skip the /1000, /10 conversions)")
    ap.add_argument("--verify", action="store_true", help="cross-check exported logic vs sklearn")
    args = ap.parse_args()

    X = load_features(args.csv, args.already_scaled)
    print(f"Training on {len(X)} rows x {X.shape[1]} features")
    if len(X) < args.max_samples:
        print(f"Warning: fewer rows than max_samples={args.max_samples}", file=sys.stderr)

    clf = IsolationForest(
        n_estimators=args.trees,
        max_samples=min(args.max_samples, len(X)),
        contamination=args.contamination,
        random_state=args.seed,
    ).fit(X)

    export_header(clf, args.out, args.csv)
    print(f"Wrote {args.out}  (offset={clf.offset_:.6f})")
    if args.verify:
        verify_export(clf, X)


if __name__ == "__main__":
    main()
